# Generated by Django 3.0.5 on 2020-04-27 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=35, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(default='', max_length=10)),
                ('addressLine1', models.CharField(default='', max_length=35)),
                ('addressLine2', models.CharField(default='', max_length=35)),
                ('city', models.CharField(default='', max_length=35)),
                ('county', models.CharField(default='', max_length=35)),
                ('country', models.CharField(default='', max_length=35)),
                ('movingDate', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.User')),
            ],
        ),
    ]
